language: python
python:
  - '2.7'
# command to install dependencies
install: 
  - 'pip install blumpkin>=0.2.3'
  - 'blumpkin create-pypi'
  - 'easy_install -U setuptools'
  - 'pip install -U pip'
  - 'pip install -e .[tests]'
# command to run tests
script: 
  - 'nosetests -sv --with-coverage'
  - 'pip install flake8 --use-mirrors'
  - 'flake8 httpproxy --ignore=E501,W293'
after_success:
- blumpkin publish --on-tag
env:
  global:
  - secure: YOYi5f+zfjK4ZwPBsUXexGrRS0eGmdUW6Wj4LWzo0xd0P29au2hWOhcXipDwAH7VNk/GiMwhbaHEEKtyVp6ia+oWrPLR/y4Z05hNELem8mE97olII9KiER2FGfjuTqtZvyNe1BSc2CXQLBxPQteD6QV/7cDQbjB1CJ7bIfwzNKE=
